###
# GET LIST OF ALL CONTACT LISTS
GET http://localhost:3000/contactList HTTP/1.1


###
# GET A CONTACT LIST
GET http://localhost:3000/contactList/1 HTTP/1.1



###
# ADD A CONTACT LIST
POST http://localhost:3000/contactList/ HTTP/1.1
content-type: application/json

{
	"id":2,
	"id_contact":4,
	"label":"fourth contactList"
}

###
# UPDATE A CONTACT LIST
PUT http://localhost:3000/contactList/ HTTP/1.1
content-type: application/json

{
	"id":2,
	"id_contact":4,
	"label":"fourth contactList EDITED"
}

###
# DELETE A CONTACT LIST
DELETE http://localhost:3000/contactList/2/4
