###
# GET LIST OF ALL MESSAGES

GET http://localhost:3000/messages HTTP/1.1
###
# GET A MESSAGE
GET http://localhost:3000/messages/1 HTTP/1.1
###
# ADD A MESSAGE

###
# UPDATE A MESSAGE

###
# DELETE A MESSAGE
